from base import conf

ADMINISTRATOR_PREFIX = "ADMINISTRATOR"


ADMINISTRATOR_LIST_URL_NAME = ADMINISTRATOR_PREFIX + conf.LIST_SUFFIX
ADMINISTRATOR_CREATE_URL_NAME = ADMINISTRATOR_PREFIX + conf.CREATE_SUFFIX
ADMINISTRATOR_DETAIL_URL_NAME = ADMINISTRATOR_PREFIX + conf.DETAIL_SUFFIX
ADMINISTRATOR_UPDATE_URL_NAME = ADMINISTRATOR_PREFIX + conf.UPDATE_SUFFIX
ADMINISTRATOR_DELETE_URL_NAME = ADMINISTRATOR_PREFIX + conf.DELETE_SUFFIX

SPECIALIST_PREFIX = "SPECIALIST"


SPECIALIST_LIST_URL_NAME = SPECIALIST_PREFIX + conf.LIST_SUFFIX
SPECIALIST_CREATE_URL_NAME = SPECIALIST_PREFIX + conf.CREATE_SUFFIX
SPECIALIST_DETAIL_URL_NAME = SPECIALIST_PREFIX + conf.DETAIL_SUFFIX
SPECIALIST_UPDATE_URL_NAME = SPECIALIST_PREFIX + conf.UPDATE_SUFFIX
SPECIALIST_DELETE_URL_NAME = SPECIALIST_PREFIX + conf.DELETE_SUFFIX

PATIENT_PREFIX = "PATIENT"


PATIENT_LIST_URL_NAME = PATIENT_PREFIX + conf.LIST_SUFFIX
PATIENT_CREATE_URL_NAME = PATIENT_PREFIX + conf.CREATE_SUFFIX
PATIENT_DETAIL_URL_NAME = PATIENT_PREFIX + conf.DETAIL_SUFFIX
PATIENT_UPDATE_URL_NAME = PATIENT_PREFIX + conf.UPDATE_SUFFIX
PATIENT_DELETE_URL_NAME = PATIENT_PREFIX + conf.DELETE_SUFFIX

