from base import conf

ADMINISTRATOR_PREFIX = "ADMINISTRATOR"


ADMINISTRATOR_LIST_URL_NAME = ADMINISTRATOR_PREFIX + conf.LIST_SUFFIX
ADMINISTRATOR_CREATE_URL_NAME = ADMINISTRATOR_PREFIX + conf.CREATE_SUFFIX
ADMINISTRATOR_DETAIL_URL_NAME = ADMINISTRATOR_PREFIX + conf.DETAIL_SUFFIX
ADMINISTRATOR_UPDATE_URL_NAME = ADMINISTRATOR_PREFIX + conf.UPDATE_SUFFIX
ADMINISTRATOR_DELETE_URL_NAME = ADMINISTRATOR_PREFIX + conf.DELETE_SUFFIX

SPECIALIST_PREFIX = "SPECIALIST"


SPECIALIST_LIST_URL_NAME = SPECIALIST_PREFIX + conf.LIST_SUFFIX
SPECIALIST_CREATE_URL_NAME = SPECIALIST_PREFIX + conf.CREATE_SUFFIX
SPECIALIST_DETAIL_URL_NAME = SPECIALIST_PREFIX + conf.DETAIL_SUFFIX
SPECIALIST_UPDATE_URL_NAME = SPECIALIST_PREFIX + conf.UPDATE_SUFFIX
SPECIALIST_DELETE_URL_NAME = SPECIALIST_PREFIX + conf.DELETE_SUFFIX
SPECIALIST_WITH_PATIENTS_URL_NAME = SPECIALIST_PREFIX + "_with_patients"

PATIENT_PREFIX = "PATIENT"


PATIENT_LIST_URL_NAME = PATIENT_PREFIX + conf.LIST_SUFFIX
PATIENT_CREATE_URL_NAME = PATIENT_PREFIX + conf.CREATE_SUFFIX
PATIENT_DETAIL_URL_NAME = PATIENT_PREFIX + conf.DETAIL_SUFFIX
PATIENT_UPDATE_URL_NAME = PATIENT_PREFIX + conf.UPDATE_SUFFIX
PATIENT_DELETE_URL_NAME = PATIENT_PREFIX + conf.DELETE_SUFFIX
PATIENT_ADD_PROCEDURE_URL_NAME = PATIENT_PREFIX + "_add_procedure"

MACHINE_PREFIX = "MACHINE"


MACHINE_LIST_URL_NAME = MACHINE_PREFIX + conf.LIST_SUFFIX
MACHINE_CREATE_URL_NAME = MACHINE_PREFIX + conf.CREATE_SUFFIX
MACHINE_DETAIL_URL_NAME = MACHINE_PREFIX + conf.DETAIL_SUFFIX
MACHINE_UPDATE_URL_NAME = MACHINE_PREFIX + conf.UPDATE_SUFFIX
MACHINE_DELETE_URL_NAME = MACHINE_PREFIX + conf.DELETE_SUFFIX

TREATMENT_PREFIX = "TREATMENT"


TREATMENT_LIST_URL_NAME = TREATMENT_PREFIX + conf.LIST_SUFFIX
TREATMENT_CREATE_URL_NAME = TREATMENT_PREFIX + conf.CREATE_SUFFIX
TREATMENT_DETAIL_URL_NAME = TREATMENT_PREFIX + conf.DETAIL_SUFFIX
TREATMENT_UPDATE_URL_NAME = TREATMENT_PREFIX + conf.UPDATE_SUFFIX
TREATMENT_DELETE_URL_NAME = TREATMENT_PREFIX + conf.DELETE_SUFFIX

PROCEDURE_PREFIX = "PROCEDURE"


PROCEDURE_LIST_URL_NAME = PROCEDURE_PREFIX + conf.LIST_SUFFIX
PROCEDURE_CREATE_URL_NAME = PROCEDURE_PREFIX + conf.CREATE_SUFFIX
PROCEDURE_DETAIL_URL_NAME = PROCEDURE_PREFIX + conf.DETAIL_SUFFIX
PROCEDURE_UPDATE_URL_NAME = PROCEDURE_PREFIX + conf.UPDATE_SUFFIX
PROCEDURE_DELETE_URL_NAME = PROCEDURE_PREFIX + conf.DELETE_SUFFIX

