# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='procedure',
            name='treatment_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Treatment'),
        ),
    ]
