# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180523_0321'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_url', models.URLField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Machine')),
            ],
        ),
        migrations.AddField(
            model_name='machineinput',
            name='machine_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MachineInstance'),
        ),
        migrations.AddField(
            model_name='machineinput',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Procedure'),
        ),
    ]
