from base import conf

APPOINTMENT_PREFIX = "APPOINTMENT"


APPOINTMENT_LIST_URL_NAME = APPOINTMENT_PREFIX + conf.LIST_SUFFIX
APPOINTMENT_CREATE_URL_NAME = APPOINTMENT_PREFIX + conf.CREATE_SUFFIX
APPOINTMENT_DETAIL_URL_NAME = APPOINTMENT_PREFIX + conf.DETAIL_SUFFIX
APPOINTMENT_UPDATE_URL_NAME = APPOINTMENT_PREFIX + conf.UPDATE_SUFFIX
APPOINTMENT_DELETE_URL_NAME = APPOINTMENT_PREFIX + conf.DELETE_SUFFIX

